name: RonanRyle
favicon: null
layout_spectrum: 0.24013195233419538
typography_spectrum: 0.5427046546246856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8405423816293478
  lightness: 0.9123286490794271
  saturation: 0.414898177376017
  rhythmicContrast: 0.6541393497027457
purpose: []
